apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-authentication
  template:
    metadata:
      labels:
        app: mysql-authentication
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: authentication
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-authentication
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
      - name: mysql-authentication
        configMap:
          name: mysql-authentication-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-authentication
spec:
  selector:
    app: mysql-authentication
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  type: ClusterIP
