version: '3'
services:
  enterdata:
    build:
      context: ./enterdata
    ports:
      - "8001:5000"
    links:
      - mysql_db
  show-results:
    build:
      context: ./show-results
    links:
      - mongodb
    ports:
      - "8004:8004"
  authentication:
    build:
      context: ./authentication
    ports:
      - "3000:3000"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=authentication
      - MYSQL_HOST=mysql_db
    links:
      - mysql_db
  analytics:
    build:
      context: ./analytics
    links:
      - mysql_db
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  mysql_db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql_db:/docker-entrypoint-initdb.d/:ro
