version: '3'
services:
  enter-data:
    build:
      context: ./enter-data
    ports:
      - "3000:3000"
  show-results:
    build:
      context: ./show-results
    ports:
      - "3001:3000"
  authentication:
    build:
      context: ./auth-svc
    ports:
      - "3002:3000"
  analytics:
    build:
      context: ./analytics-svc
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  mysql:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: data-collection
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - /data/mysql:/var/lib/mysql
